### ISSUE TITLE
Rules for a score with quantity element with 1 quality real unit doesnt work PMP guideline

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#429]
GDL2 Editor version
Steps to reproduce issue: PMP guideline with a score (quantity element/property qualified real/ unit is 1). when I try to make a rule for interpratation it does not work. it just give the score but not not the interpretation. in the rule condition I used constant compa
[openEHR-EHR-OBSERVATION.preoperative_mortality_predictor_pmp_score.v0.zip](https://github.com/gdl-lang/common-clinical-models/files/4385781/openEHR-EHR-OBSERVATION.preoperative_mortality_predictor_pmp_score.v0.zip)
rison (score<=5) and Rule action I used set value score magnitude to 0.1%.  
Expected outcome: for a score<=5 I have to have a outcome.
Actual outcome: This rule doesn't which means I receive only the score not the interpretation based on the rule condition and rule action.
Attached any archetypes/guidelines 
Provide links to resources: https://www.mdcalc.com/preoperative-mortality-predictor-pmp-score#evidence

**Comment by isabellejensen** [comment]
@MaryamRazavi 
Instead of constant comparison, use attribute comparison for score.magnitude. 

If you need to compare with a negativa value you can use single quotes in the expression editor, i.e.
score.magnitude < '-1' 
etc.
