### ISSUE TITLE
Entry for Quantity type element is always being rounded

### ISSUE THREAD

**Issue by winnerng** [gdl-lang/common-clinical-models#438]
[Issue-quantity_data_rounded.zip](https://github.com/gdl-lang/common-clinical-models/files/4438439/Issue-quantity_data_rounded.zip)

Hi team!
I've been trying to revise the attached guideline. I found out that some data entry for the quantity type element in decimals always get rounded upon the execution thus affecting the input for the rules and eventually the result and interpretation.

![image](https://user-images.githubusercontent.com/49078821/78560738-d5373480-7816-11ea-8c2f-23c7a3afa627.png)

I've tried to go to the archetypes, adjusting the "limit decimals" for instance, but didn't solve the rounding issue.

Will greatly appreciate if anyone could help me with this. Thanks

Regards,
Winner

**Comment by isabellejensen** [comment]
Hi Winner,
This is a known bug which I have reported. Until it is fixed there is no way to work around it in the execution tab (that I know of). However, the decimals work as expected in the test tab so you can edit your test cases there to make sure that everything work correctly. 

Thanks for reporting!
Regards, Isabelle

**Comment by winnerng** [comment]
Ah I see, if all the test fixtures passed, is it okay to create the pull request then?
