### ISSUE TITLE
round up a number

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#466]

**Comment by MaryamRazavi** [comment]
How can we create a rule to round a number in Gdl? for example 12.5 round up to 13.

**Comment by KalliamvakosKon** [comment]
Hi @MaryamRazavi, you add a round function like this:

score.magnitude=round(variable1.magnitude + variable2.magnitude....)

For a better example you can take a look in the guideline Osteoporosis_Risk_score_guideline on master branch.
