### ISSUE TITLE
Cannot see some values have been changed on the notepad in GDL

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#476]
For one factor, I had similar values. So, I have edited them in the NotePad and saved the archetype, but when I put them in gdl.  only those factors that were changed in the NotePad could be seen, and not those that not been chaned. 
![8d8a0904-0b8b-40b6-a8f5-e0f83c5a5c5a](https://user-images.githubusercontent.com/58226623/82663520-1bfab580-9c30-11ea-8688-98da8918e4bf.JPG)
![7be07ce7-cb7b-4a97-9560-89de9a47c032](https://user-images.githubusercontent.com/58226623/82663526-2026d300-9c30-11ea-8095-8626f1131610.JPG)

**Comment by KalliamvakosKon** [comment]
@MaryamRazavi I'm not familiar with NetPad. My guess would be that NetPad somehow could have messed up the spaces (tab instead of space). I would recommend that you use Notepad++ to edit the archetype from the beginning and try again. Let me know if the problem persists after this.

**Comment by MaryamRazavi** [comment]
@KalliamvakosKon Sorry typo. 
I ment Notepad, Yes, I will try  it again.

**Comment by MaryamRazavi** [comment]
@KalliamvakosKon I tried to edit values based on your recommendations. Still one value is missing after editing in Notepad++. 
![Edited Archetype](https://user-images.githubusercontent.com/58226623/83124702-d5490780-a0d6-11ea-98ea-abc36161c6d7.png)
![notepad screen shot](https://user-images.githubusercontent.com/58226623/83124849-0a555a00-a0d7-11ea-8a3e-6b0fb0551195.png)

**Comment by KalliamvakosKon** [comment]
Hi @MaryamRazavi thanks for the update. I think there is a bug in the GDL2 editor. I tried it also myself and I got the same issue as you. However when I imported it to the KM all the selections were available.

I will log an issue on the GDL2 editor for our developers to address in the future.

In the meantime give me a heads-up when you encounter the same issue so that I can check in the KM if things are ok.

**Comment by MaryamRazavi** [comment]
Hi @KalliamvakosKon. Thank you for the update. Sure, I will do that. :)))

**Comment by danielkesz** [comment]
My guess would be that the values are not in order: 0, 1, 0, 1, 1 and the GDL Editor might expect this as the Archetype Editor saves the files in this order, so you get only those values, which are in order and not those, which are not. This is a guess, but may be you can try it out.

**Comment by KalliamvakosKon** [comment]
Thanks @danielkesz good point. However it is still a bug because the GDL2 Editor should respect the sequence of the archetype.

**Comment by MaryamRazavi** [comment]
@danielkesz I tried them also in order like 0 0 1 1 1 but still first 0 was not visible in GDL2.
