### ISSUE TITLE
IMPACT Guideline

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#512]
IMPACT link from Medcalc: https://www.mdcalc.com/impact-score-outcomes-head-injury#evidence
Question 1: Which reference should be used for IMPACT guideline ?
First Ref: Medcalc evidence 
![IMPACT coefficient](https://user-images.githubusercontent.com/58226623/85682570-b71df980-b6cc-11ea-8c7c-c532a6635cc1.png)
or
Second ref: Score chart for 6 mo outcome after TBI 
![IMPACT score chart](https://user-images.githubusercontent.com/58226623/85682353-7e7e2000-b6cc-11ea-9263-60e6ae9a0891.png)

Question 2: Can ref#1 be modeled in OpenEHR? if yes how?

Question 3: How can I use negative exponent in GDL editor?
IMPACT formula is=Probability of 6-month mortality or unfavorable outcome = 1 / (1 + e-x)
I create this expression in the rule "1/(1+exp(-[Lp mortality].magnitude)))" but I got error. 
@KalliamvakosKon

**Comment by KalliamvakosKon** [comment]
@MaryamRazavi I believe I answered questions 1 and 2 via PM. As for question 3 can you add here the error you get?

**Comment by winnerng** [comment]
@MaryamRazavi , for negative value you need to envelop the value with ' character. 
So, in your case, I believe the expression should be 1/(1+exp('-[Lp mortality].magnitude')))
cmiiw.
