### ISSUE TITLE
Additional condition appears when setting up rule with OR function

### ISSUE THREAD

**Issue by winnerng** [gdl-lang/common-clinical-models#562]
Hi @KalliamvakosKon ,
When we are setting up the conditions using OR, if we have created the first statement before dragging in the OR function, then the first statement will re-appear. So, instead of getting (condition A or condition B), we will end up with (condition A and (condition A or condition B)) should we forget to remove the condition A afterward. Please see the attached video. 

[or_function_bug.MP4.zip](https://github.com/gdl-lang/common-clinical-models/files/4897474/or_function_bug.MP4.zip)

**Comment by KalliamvakosKon** [comment]
Thanks @winnerng I reported the issue now to our team. Will close this one for now.
