### ISSUE TITLE
Bug in element path when setting up rules

### ISSUE THREAD

**Issue by winnerng** [gdl-lang/common-clinical-models#564]
Hi again @KalliamvakosKon ,
This is another one. So if we are to set rules using different elements that have same name, i.e. Age (quantity) and Age (ordinal), the element path will get mixed up even though we have clicked on correct element item when setting the rule. To fix it, we have to go to the GDL tab and change the code, but sometimes when developing the guideline further, it will revert back, and we have to fix the code in GDL tab again. See the attached video and I have uploaded the file for you to try if necessary. Thank you.

[Element path issue.zip](https://github.com/gdl-lang/common-clinical-models/files/4901864/Element.path.issue.zip)

**Comment by KalliamvakosKon** [comment]
Thanks @winnerng I have reported the issue now to our team. Closing for now.
