### ISSUE TITLE
 Decimal numbers less than 1 that can have between 1 and 9 decimal places

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#591]
How to write a rule condition to compare decimal numbers less than 1 that can have between 1 and 9 decimal places?
![HIV Rule](https://user-images.githubusercontent.com/58226623/87953507-6cb15200-caab-11ea-836e-a99aef887e93.png)

![Result HIV](https://user-images.githubusercontent.com/58226623/87953573-805cb880-caab-11ea-8a42-1efb1ebaa04f.png)
Guideline: https://www.mdcalc.com/hiv-needle-stick-risk-assessment-stratification-protocol-rasp#evidence
Error: Apparently it is not possible for GDL 2 Editor to compare the numbers between 1/1000-1/10,000. How can I write a rule for this condition?
@rashmidamu

**Comment by rashmidamu** [comment]
The issue occurred due to a bug in the GDL2 editor which would be fixed in the latest version.
