### ISSUE TITLE
Decimal input round up or round down in fixture 

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#592]
I have a decimal input for serum dig level which will be round up or down in fixture. If the digit is less than 5, round the previous digit down; if it's 5 or greater, round the previous digit up. 
![Digifab Round decimal number](https://user-images.githubusercontent.com/58226623/87956093-e434b080-caae-11ea-9826-f412e3a0c4f7.png)
Guideline:https://www.mdcalc.com/digifab-digibind-dosing-digoxin-poisoning#evidence
@rashmidamu

**Comment by rashmidamu** [comment]
@MaryamRazavi, it is probably a bug in the gdl2 editor. It executes as expected in the gdl2 engine. So, it should work when you use the fixture generator to create the test fixture for this guideline.

**Comment by MaryamRazavi** [comment]
@rashmidamu This issue is fixed in gdl 2 editor preview 4.

**Comment by rashmidamu** [comment]
Great!
