### ISSUE TITLE
Set one warning for an input with two different units!

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#674]
Guideline: Donor Lymphocyte Infusion (DLI) Volume 
https://www.mdcalc.com/donor-lymphocyte-infusion-dli-volume#use-cases
input: Donor WBC has two units [10^3 cells/microL and 10^9 cells/L] 
The numerical spectrum representing the warning is the same in both units. For example, for very high, the numerical range for both Donor WBC units is greater than 500. OR operator cannot be used because it displays a warning for one of the units.
@KalliamvakosKon  How this problem can be fixed?

**Comment by KalliamvakosKon** [comment]
Per UCUM (https://ucum.org/ucum.html) your units should be 10*3/uL and 10*9/L. Currently there is a known bug that can occur when units contains special characters. Here are some solutions:

1. Using constant comparison: Donor WBC>500 10*3/uL OR Donor WBC>500 10*9/L
2. If the above bugs out Use expression: Donor WBC.magnitude>500 AND (Donor WBC.unit=='10\*3/uL' OR Donor WBC.unit=='10\*9/L')
3. If the above bugs as well Use expression: Donor WBC.magnitude>500. This will require that the archetype contains only those two units and no other.

**Comment by MaryamRazavi** [comment]
1. With the first approach "Using constant comparison: Donor WBC>500 10*3/uL OR Donor WBC>500 10*9/L", I have got this notification "There are incomplete elements/expressions.
Are you sure you want to switch tab?" and also this just  working for one warning, this means all the warning message are same as the first warning I have set for this input! (even for warning too low or very high I see Too high). 
2. I didn't get any notification but still same situation as above.
3. Do you mean I need a separate archetype for just for Donor WBC and its units?
or do you mean in the same archetype Donor WBC should has these two units and no other?
