### ISSUE TITLE
Terminology Error 

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#675]
" Parsing error: term with id gt0016 was referred in the guide but not defined in terminology."
Why does this error happen?
How this error can be fixed?
@KalliamvakosKon

**Comment by KalliamvakosKon** [comment]
@MaryamRazavi on which project do you have this issue? It's very hard to tell without a means to reproduce :(

**Comment by MaryamRazavi** [comment]
@KalliamvakosKon 
Guideline: Donor Lymphocyte Infusion (DLI) Volume
https://www.mdcalc.com/donor-lymphocyte-infusion-dli-volume#use-cases
But then also when I start to create another guideline the same error appears! which was strange because there were only 14 codes in terminology. And actually I restarted everything and now there is no error!

**Comment by KalliamvakosKon** [comment]
@MaryamRazavi ok, this good be something with maybe your machine became too slow and got the editor out of sync somehow. I will close the issue for now but please keep an eye for it if it happens again.
