### ISSUE TITLE
problem with constant comparison and ordinal element

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#690]
Guideline: UCLA Integrated Staging System (UISS) for Renal Cell Carcinoma (RCC) #679 
Reproducing the issue: 
In the archetype one element has been changed from coded text to ordinal. 
Rules with that ordinal element and constant comparison and "< or >" are not executing! 
However, the same rules are working perfectly when constant comparison is being used with "=". 
@KalliamvakosKon

**Comment by rashmidamu** [comment]
Here, to compare the ordinal values of variables, Attribute.[@value] must be used instead of Constant comparison.
